Reorganize project structure
goiabada/gomu pull request #4
Opened 2019-07-25 21:08 UTC by GArmane

2019-07-25 21:24 UTC, GArmane commented
Need fixes

2019-07-26 00:32 UTC, Emethium approved these changes

2019-07-26 13:03 UTC, alvadorn requested changes

2019-07-26 13:03 UTC, Alvadorn commented on pkg/gba/core.go
> +import arm7 "github.com/goiabada/gomu/pkg/arm7"
Não precisa prefixar o arm7, ele sempre pega por padrão a última pasta hehe.
Pode ser apenas:
`import "github.com/goiabada/gomu/pkg/arm7"`

2019-07-31 18:56 UTC, GArmane commented on pkg/gba/core.go
> +import arm7 "github.com/goiabada/gomu/pkg/arm7"
Done

2019-07-31 19:00 UTC, Alvadorn commented
@GArmane , o ideal é que quando você exporta uma função você coloque algum comentário nela.

Ex: 
```go
// Sum returns a sum of 'a' and 'b' arguments
func Sum(a, b int) int {
 return a + b
}
```

2019-08-01 03:27 UTC, alvadorn approved these changes

2019-08-01 03:28 UTC, merged